# Generated by Django 3.2.7 on 2021-11-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_on',
        ),
    ]
